// <auto-generated />
namespace SocialNet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removedfriendshipcollectionfromuserprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedfriendshipcollectionfromuserprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "201803131840422_removed friendship collection from user profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
